FROM jenkins/jenkins:lts
USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io

# Grant jenkins user access to run docker commands
RUN usermod -aG docker jenkins

USER jenkins
